#!/bin/bash

clang -std=c99 -pedantic -g -O1 \
    -fsanitize=address,undefined \
    -Wall \
    -Wextra \
    -Wnull-dereference \
    -Wno-unused-parameter \
    serialization_test.c \
    -o serialization_test

mkdir -p serialized_test_cases

for file in test_cases/*; do
    target="${file##*/}"
    target="${target%.ptxt}"
    ./serialization_test --serialize "$file" "serialized_test_cases/$target.ast"
done
